# Generated by Django 5.0 on 2023-12-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingen_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='expiration_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
