# Generated by Django 5.0 on 2023-12-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingen_api', '0002_alter_quotation_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
    ]
